version: '2'
services:
    shell-app:
        image: shell
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://shell-mysql:3306/shell?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shell-mysql:
        extends:
            file: mysql.yml
            service: shell-mysql
